// GENERATED by scripts/gen-types.sh from the public schema. Do not edit by hand.

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

export type Database = {
  public: {
    Tables: {
      approvals: {
        Row: {
          approved_by: string;
          artifact_id: string;
          at: string;
          gate_type: Database['public']['Enums']['gate_type'];
          id: string;
          role: Database['public']['Enums']['approver_role'];
        };
        ComputedFields: never;
        Insert: {
          approved_by: string;
          artifact_id: string;
          at?: string;
          gate_type: Database['public']['Enums']['gate_type'];
          id?: string;
          role: Database['public']['Enums']['approver_role'];
        };
        Update: {
          approved_by?: string;
          artifact_id?: string;
          at?: string;
          gate_type?: Database['public']['Enums']['gate_type'];
          id?: string;
          role?: Database['public']['Enums']['approver_role'];
        };
        Relationships: [
          {
            foreignKeyName: 'approvals_artifact_id_fkey';
            columns: ['artifact_id'];
            isOneToOne: false;
            referencedRelation: 'artifacts';
            referencedColumns: ['id'];
          },
        ];
      };
      artifacts: {
        Row: {
          client_visible: boolean;
          content: NonNullable<Json>;
          created_at: string;
          id: string;
          project_id: string;
          status: Database['public']['Enums']['artifact_status'];
          type: string;
          version: number;
        };
        ComputedFields: never;
        Insert: {
          client_visible?: boolean;
          content?: NonNullable<Json>;
          created_at?: string;
          id?: string;
          project_id: string;
          status?: Database['public']['Enums']['artifact_status'];
          type: string;
          version?: number;
        };
        Update: {
          client_visible?: boolean;
          content?: NonNullable<Json>;
          created_at?: string;
          id?: string;
          project_id?: string;
          status?: Database['public']['Enums']['artifact_status'];
          type?: string;
          version?: number;
        };
        Relationships: [
          {
            foreignKeyName: 'artifacts_project_id_fkey';
            columns: ['project_id'];
            isOneToOne: false;
            referencedRelation: 'projects';
            referencedColumns: ['id'];
          },
        ];
      };
      backlog_items: {
        Row: {
          answer_action: Database['public']['Enums']['answer_action'] | null;
          ask_client: boolean;
          assumption: string | null;
          client_answer: string | null;
          context: string | null;
          created_at: string;
          id: string;
          owner_answer: string | null;
          project_id: string;
          question: string;
          round: number | null;
          status: Database['public']['Enums']['backlog_status'];
        };
        ComputedFields: never;
        Insert: {
          answer_action?: Database['public']['Enums']['answer_action'] | null;
          ask_client?: boolean;
          assumption?: string | null;
          client_answer?: string | null;
          context?: string | null;
          created_at?: string;
          id?: string;
          owner_answer?: string | null;
          project_id: string;
          question: string;
          round?: number | null;
          status?: Database['public']['Enums']['backlog_status'];
        };
        Update: {
          answer_action?: Database['public']['Enums']['answer_action'] | null;
          ask_client?: boolean;
          assumption?: string | null;
          client_answer?: string | null;
          context?: string | null;
          created_at?: string;
          id?: string;
          owner_answer?: string | null;
          project_id?: string;
          question?: string;
          round?: number | null;
          status?: Database['public']['Enums']['backlog_status'];
        };
        Relationships: [
          {
            foreignKeyName: 'backlog_items_project_id_fkey';
            columns: ['project_id'];
            isOneToOne: false;
            referencedRelation: 'projects';
            referencedColumns: ['id'];
          },
        ];
      };
      change_requests: {
        Row: {
          created_at: string;
          created_by: string | null;
          decision: Database['public']['Enums']['change_decision'] | null;
          description: string;
          id: string;
          impact_note: string | null;
          project_id: string;
          status: Database['public']['Enums']['change_status'];
          submitted_by: Database['public']['Enums']['approver_role'];
        };
        ComputedFields: never;
        Insert: {
          created_at?: string;
          created_by?: string | null;
          decision?: Database['public']['Enums']['change_decision'] | null;
          description: string;
          id?: string;
          impact_note?: string | null;
          project_id: string;
          status?: Database['public']['Enums']['change_status'];
          submitted_by?: Database['public']['Enums']['approver_role'];
        };
        Update: {
          created_at?: string;
          created_by?: string | null;
          decision?: Database['public']['Enums']['change_decision'] | null;
          description?: string;
          id?: string;
          impact_note?: string | null;
          project_id?: string;
          status?: Database['public']['Enums']['change_status'];
          submitted_by?: Database['public']['Enums']['approver_role'];
        };
        Relationships: [
          {
            foreignKeyName: 'change_requests_project_id_fkey';
            columns: ['project_id'];
            isOneToOne: false;
            referencedRelation: 'projects';
            referencedColumns: ['id'];
          },
        ];
      };
      clients: {
        Row: {
          created_at: string;
          email: string;
          id: string;
          project_id: string;
        };
        ComputedFields: never;
        Insert: {
          created_at?: string;
          email: string;
          id: string;
          project_id: string;
        };
        Update: {
          created_at?: string;
          email?: string;
          id?: string;
          project_id?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'clients_project_id_fkey';
            columns: ['project_id'];
            isOneToOne: false;
            referencedRelation: 'projects';
            referencedColumns: ['id'];
          },
        ];
      };
      comments: {
        Row: {
          artifact_id: string | null;
          body: string;
          created_at: string;
          created_by: string | null;
          id: string;
          kind: Database['public']['Enums']['comment_kind'];
          owner_disposition: Database['public']['Enums']['comment_disposition'] | null;
          project_id: string;
        };
        ComputedFields: never;
        Insert: {
          artifact_id?: string | null;
          body: string;
          created_at?: string;
          created_by?: string | null;
          id?: string;
          kind?: Database['public']['Enums']['comment_kind'];
          owner_disposition?: Database['public']['Enums']['comment_disposition'] | null;
          project_id: string;
        };
        Update: {
          artifact_id?: string | null;
          body?: string;
          created_at?: string;
          created_by?: string | null;
          id?: string;
          kind?: Database['public']['Enums']['comment_kind'];
          owner_disposition?: Database['public']['Enums']['comment_disposition'] | null;
          project_id?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'comments_artifact_id_fkey';
            columns: ['artifact_id'];
            isOneToOne: false;
            referencedRelation: 'artifacts';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'comments_project_id_fkey';
            columns: ['project_id'];
            isOneToOne: false;
            referencedRelation: 'projects';
            referencedColumns: ['id'];
          },
        ];
      };
      email_log: {
        Row: {
          claimed_at: string;
          dedupe_key: string;
          error: string | null;
          event: string;
          id: string;
          project_id: string | null;
          recipient: string;
          recipient_role: Database['public']['Enums']['approver_role'];
          sent_at: string | null;
        };
        ComputedFields: never;
        Insert: {
          claimed_at?: string;
          dedupe_key: string;
          error?: string | null;
          event: string;
          id?: string;
          project_id?: string | null;
          recipient: string;
          recipient_role: Database['public']['Enums']['approver_role'];
          sent_at?: string | null;
        };
        Update: {
          claimed_at?: string;
          dedupe_key?: string;
          error?: string | null;
          event?: string;
          id?: string;
          project_id?: string | null;
          recipient?: string;
          recipient_role?: Database['public']['Enums']['approver_role'];
          sent_at?: string | null;
        };
        Relationships: [
          {
            foreignKeyName: 'email_log_project_id_fkey';
            columns: ['project_id'];
            isOneToOne: false;
            referencedRelation: 'projects';
            referencedColumns: ['id'];
          },
        ];
      };
      gate_config: {
        Row: {
          escalate_after_hours: number;
          gate_type: Database['public']['Enums']['gate_type'];
          gatekeeper: Database['public']['Enums']['approver_role'];
          id: string;
          project_id: string | null;
          stage: Database['public']['Enums']['stage'];
        };
        ComputedFields: never;
        Insert: {
          escalate_after_hours?: number;
          gate_type: Database['public']['Enums']['gate_type'];
          gatekeeper: Database['public']['Enums']['approver_role'];
          id?: string;
          project_id?: string | null;
          stage: Database['public']['Enums']['stage'];
        };
        Update: {
          escalate_after_hours?: number;
          gate_type?: Database['public']['Enums']['gate_type'];
          gatekeeper?: Database['public']['Enums']['approver_role'];
          id?: string;
          project_id?: string | null;
          stage?: Database['public']['Enums']['stage'];
        };
        Relationships: [
          {
            foreignKeyName: 'gate_config_project_id_fkey';
            columns: ['project_id'];
            isOneToOne: false;
            referencedRelation: 'projects';
            referencedColumns: ['id'];
          },
        ];
      };
      intake_responses: {
        Row: {
          answer: Json | null;
          asked_by: Database['public']['Enums']['asked_by'];
          id: string;
          project_id: string;
          question_id: string;
          round: number;
          updated_at: string;
        };
        ComputedFields: never;
        Insert: {
          answer?: Json | null;
          asked_by: Database['public']['Enums']['asked_by'];
          id?: string;
          project_id: string;
          question_id: string;
          round: number;
          updated_at?: string;
        };
        Update: {
          answer?: Json | null;
          asked_by?: Database['public']['Enums']['asked_by'];
          id?: string;
          project_id?: string;
          question_id?: string;
          round?: number;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'intake_responses_project_id_fkey';
            columns: ['project_id'];
            isOneToOne: false;
            referencedRelation: 'projects';
            referencedColumns: ['id'];
          },
        ];
      };
      intake_rounds: {
        Row: {
          created_at: string;
          id: string;
          project_id: string;
          reviewed_at: string | null;
          round: number;
          status: Database['public']['Enums']['intake_round_status'];
          submitted_at: string | null;
        };
        ComputedFields: never;
        Insert: {
          created_at?: string;
          id?: string;
          project_id: string;
          reviewed_at?: string | null;
          round: number;
          status?: Database['public']['Enums']['intake_round_status'];
          submitted_at?: string | null;
        };
        Update: {
          created_at?: string;
          id?: string;
          project_id?: string;
          reviewed_at?: string | null;
          round?: number;
          status?: Database['public']['Enums']['intake_round_status'];
          submitted_at?: string | null;
        };
        Relationships: [
          {
            foreignKeyName: 'intake_rounds_project_id_fkey';
            columns: ['project_id'];
            isOneToOne: false;
            referencedRelation: 'projects';
            referencedColumns: ['id'];
          },
        ];
      };
      intake_templates: {
        Row: {
          created_at: string;
          id: string;
          industry: string;
          sections: NonNullable<Json>;
          status: Database['public']['Enums']['template_status'];
          version: number;
        };
        ComputedFields: never;
        Insert: {
          created_at?: string;
          id?: string;
          industry: string;
          sections?: NonNullable<Json>;
          status?: Database['public']['Enums']['template_status'];
          version?: number;
        };
        Update: {
          created_at?: string;
          id?: string;
          industry?: string;
          sections?: NonNullable<Json>;
          status?: Database['public']['Enums']['template_status'];
          version?: number;
        };
        Relationships: [];
      };
      owner_notes: {
        Row: {
          body: string;
          created_at: string;
          id: string;
          project_id: string;
          updated_at: string;
        };
        ComputedFields: never;
        Insert: {
          body: string;
          created_at?: string;
          id?: string;
          project_id: string;
          updated_at?: string;
        };
        Update: {
          body?: string;
          created_at?: string;
          id?: string;
          project_id?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'owner_notes_project_id_fkey';
            columns: ['project_id'];
            isOneToOne: false;
            referencedRelation: 'projects';
            referencedColumns: ['id'];
          },
        ];
      };
      owners: {
        Row: {
          created_at: string;
          id: string;
        };
        ComputedFields: never;
        Insert: {
          created_at?: string;
          id: string;
        };
        Update: {
          created_at?: string;
          id?: string;
        };
        Relationships: [];
      };
      prd_feedback: {
        Row: {
          artifact_id: string;
          body: string;
          created_at: string;
          created_by: string;
          id: string;
          project_id: string;
        };
        ComputedFields: never;
        Insert: {
          artifact_id: string;
          body: string;
          created_at?: string;
          created_by: string;
          id?: string;
          project_id: string;
        };
        Update: {
          artifact_id?: string;
          body?: string;
          created_at?: string;
          created_by?: string;
          id?: string;
          project_id?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'prd_feedback_artifact_id_fkey';
            columns: ['artifact_id'];
            isOneToOne: false;
            referencedRelation: 'artifacts';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'prd_feedback_project_id_fkey';
            columns: ['project_id'];
            isOneToOne: false;
            referencedRelation: 'projects';
            referencedColumns: ['id'];
          },
        ];
      };
      projects: {
        Row: {
          close_reason: Database['public']['Enums']['close_reason'] | null;
          created_at: string;
          data_deleted_at: string | null;
          github_repo: string | null;
          id: string;
          industry: string | null;
          intake_template_id: string | null;
          intake_template_snapshot: Json | null;
          name: string;
          retention_until: string | null;
          round_plan: Json | null;
          stage: Database['public']['Enums']['stage'];
          status: Database['public']['Enums']['project_status'];
          token_budget: number | null;
          vercel_project_id: string | null;
        };
        ComputedFields: never;
        Insert: {
          close_reason?: Database['public']['Enums']['close_reason'] | null;
          created_at?: string;
          data_deleted_at?: string | null;
          github_repo?: string | null;
          id?: string;
          industry?: string | null;
          intake_template_id?: string | null;
          intake_template_snapshot?: Json | null;
          name: string;
          retention_until?: string | null;
          round_plan?: Json | null;
          stage?: Database['public']['Enums']['stage'];
          status?: Database['public']['Enums']['project_status'];
          token_budget?: number | null;
          vercel_project_id?: string | null;
        };
        Update: {
          close_reason?: Database['public']['Enums']['close_reason'] | null;
          created_at?: string;
          data_deleted_at?: string | null;
          github_repo?: string | null;
          id?: string;
          industry?: string | null;
          intake_template_id?: string | null;
          intake_template_snapshot?: Json | null;
          name?: string;
          retention_until?: string | null;
          round_plan?: Json | null;
          stage?: Database['public']['Enums']['stage'];
          status?: Database['public']['Enums']['project_status'];
          token_budget?: number | null;
          vercel_project_id?: string | null;
        };
        Relationships: [
          {
            foreignKeyName: 'projects_intake_template_id_fkey';
            columns: ['intake_template_id'];
            isOneToOne: false;
            referencedRelation: 'intake_templates';
            referencedColumns: ['id'];
          },
        ];
      };
      qc_runs: {
        Row: {
          checklist: Json | null;
          id: string;
          lighthouse: Json | null;
          project_id: string;
          run_at: string;
        };
        ComputedFields: never;
        Insert: {
          checklist?: Json | null;
          id?: string;
          lighthouse?: Json | null;
          project_id: string;
          run_at?: string;
        };
        Update: {
          checklist?: Json | null;
          id?: string;
          lighthouse?: Json | null;
          project_id?: string;
          run_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'qc_runs_project_id_fkey';
            columns: ['project_id'];
            isOneToOne: false;
            referencedRelation: 'projects';
            referencedColumns: ['id'];
          },
        ];
      };
      rounds: {
        Row: {
          branch: string | null;
          change_request_id: string | null;
          claims: NonNullable<Json>;
          claims_cleared_at: string | null;
          feedback_count: number;
          id: string;
          number: number;
          pr_number: number | null;
          pr_url: string | null;
          preview_url: string | null;
          project_id: string;
          scope: Json | null;
          status: Database['public']['Enums']['round_status'];
        };
        ComputedFields: never;
        Insert: {
          branch?: string | null;
          change_request_id?: string | null;
          claims?: NonNullable<Json>;
          claims_cleared_at?: string | null;
          feedback_count?: number;
          id?: string;
          number: number;
          pr_number?: number | null;
          pr_url?: string | null;
          preview_url?: string | null;
          project_id: string;
          scope?: Json | null;
          status?: Database['public']['Enums']['round_status'];
        };
        Update: {
          branch?: string | null;
          change_request_id?: string | null;
          claims?: NonNullable<Json>;
          claims_cleared_at?: string | null;
          feedback_count?: number;
          id?: string;
          number?: number;
          pr_number?: number | null;
          pr_url?: string | null;
          preview_url?: string | null;
          project_id?: string;
          scope?: Json | null;
          status?: Database['public']['Enums']['round_status'];
        };
        Relationships: [
          {
            foreignKeyName: 'rounds_change_request_id_fkey';
            columns: ['change_request_id'];
            isOneToOne: false;
            referencedRelation: 'change_requests';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'rounds_project_id_fkey';
            columns: ['project_id'];
            isOneToOne: false;
            referencedRelation: 'projects';
            referencedColumns: ['id'];
          },
        ];
      };
      run_approvals: {
        Row: {
          command: string;
          decided_at: string | null;
          decided_by: string | null;
          id: string;
          kind: string;
          requested_at: string;
          run_id: string;
          status: Database['public']['Enums']['run_approval_status'];
        };
        ComputedFields: never;
        Insert: {
          command: string;
          decided_at?: string | null;
          decided_by?: string | null;
          id?: string;
          kind: string;
          requested_at?: string;
          run_id: string;
          status?: Database['public']['Enums']['run_approval_status'];
        };
        Update: {
          command?: string;
          decided_at?: string | null;
          decided_by?: string | null;
          id?: string;
          kind?: string;
          requested_at?: string;
          run_id?: string;
          status?: Database['public']['Enums']['run_approval_status'];
        };
        Relationships: [
          {
            foreignKeyName: 'run_approvals_run_id_fkey';
            columns: ['run_id'];
            isOneToOne: false;
            referencedRelation: 'stage_runs';
            referencedColumns: ['id'];
          },
        ];
      };
      run_logs: {
        Row: {
          created_at: string;
          id: number;
          level: string;
          message: string;
          run_id: string;
        };
        ComputedFields: never;
        Insert: {
          created_at?: string;
          id?: never;
          level?: string;
          message: string;
          run_id: string;
        };
        Update: {
          created_at?: string;
          id?: never;
          level?: string;
          message?: string;
          run_id?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'run_logs_run_id_fkey';
            columns: ['run_id'];
            isOneToOne: false;
            referencedRelation: 'stage_runs';
            referencedColumns: ['id'];
          },
        ];
      };
      skill_uses: {
        Row: {
          id: string;
          mark: Database['public']['Enums']['skill_mark'];
          marked_at: string;
          project_id: string;
          skill: string;
          stage: Database['public']['Enums']['stage'];
        };
        ComputedFields: never;
        Insert: {
          id?: string;
          mark: Database['public']['Enums']['skill_mark'];
          marked_at?: string;
          project_id: string;
          skill: string;
          stage: Database['public']['Enums']['stage'];
        };
        Update: {
          id?: string;
          mark?: Database['public']['Enums']['skill_mark'];
          marked_at?: string;
          project_id?: string;
          skill?: string;
          stage?: Database['public']['Enums']['stage'];
        };
        Relationships: [
          {
            foreignKeyName: 'skill_uses_project_id_fkey';
            columns: ['project_id'];
            isOneToOne: false;
            referencedRelation: 'projects';
            referencedColumns: ['id'];
          },
        ];
      };
      skills_registry: {
        Row: {
          approved_at: string | null;
          approved_by: string | null;
          created_at: string;
          generalization_report: Json | null;
          id: string;
          name: string;
          path: string;
          project_id: string | null;
          scope: Database['public']['Enums']['skill_scope'];
          version: number;
        };
        ComputedFields: never;
        Insert: {
          approved_at?: string | null;
          approved_by?: string | null;
          created_at?: string;
          generalization_report?: Json | null;
          id?: string;
          name: string;
          path: string;
          project_id?: string | null;
          scope: Database['public']['Enums']['skill_scope'];
          version?: number;
        };
        Update: {
          approved_at?: string | null;
          approved_by?: string | null;
          created_at?: string;
          generalization_report?: Json | null;
          id?: string;
          name?: string;
          path?: string;
          project_id?: string | null;
          scope?: Database['public']['Enums']['skill_scope'];
          version?: number;
        };
        Relationships: [
          {
            foreignKeyName: 'skills_registry_project_id_fkey';
            columns: ['project_id'];
            isOneToOne: false;
            referencedRelation: 'projects';
            referencedColumns: ['id'];
          },
        ];
      };
      stage_runs: {
        Row: {
          attempts: number;
          claimed_by: string | null;
          finished_at: string | null;
          heartbeat_at: string | null;
          id: string;
          project_id: string;
          queued_at: string;
          stage: Database['public']['Enums']['stage'];
          started_at: string | null;
          status: Database['public']['Enums']['run_status'];
          tokens_used: number;
        };
        ComputedFields: never;
        Insert: {
          attempts?: number;
          claimed_by?: string | null;
          finished_at?: string | null;
          heartbeat_at?: string | null;
          id?: string;
          project_id: string;
          queued_at?: string;
          stage: Database['public']['Enums']['stage'];
          started_at?: string | null;
          status?: Database['public']['Enums']['run_status'];
          tokens_used?: number;
        };
        Update: {
          attempts?: number;
          claimed_by?: string | null;
          finished_at?: string | null;
          heartbeat_at?: string | null;
          id?: string;
          project_id?: string;
          queued_at?: string;
          stage?: Database['public']['Enums']['stage'];
          started_at?: string | null;
          status?: Database['public']['Enums']['run_status'];
          tokens_used?: number;
        };
        Relationships: [
          {
            foreignKeyName: 'stage_runs_project_id_fkey';
            columns: ['project_id'];
            isOneToOne: false;
            referencedRelation: 'projects';
            referencedColumns: ['id'];
          },
        ];
      };
      uploads: {
        Row: {
          created_at: string;
          id: string;
          kind: string;
          mime_type: string;
          optional: boolean;
          project_id: string;
          scan_status: Database['public']['Enums']['upload_scan_status'];
          size_bytes: number;
          storage_path: string;
        };
        ComputedFields: never;
        Insert: {
          created_at?: string;
          id?: string;
          kind: string;
          mime_type: string;
          optional?: boolean;
          project_id: string;
          scan_status?: Database['public']['Enums']['upload_scan_status'];
          size_bytes: number;
          storage_path: string;
        };
        Update: {
          created_at?: string;
          id?: string;
          kind?: string;
          mime_type?: string;
          optional?: boolean;
          project_id?: string;
          scan_status?: Database['public']['Enums']['upload_scan_status'];
          size_bytes?: number;
          storage_path?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'uploads_project_id_fkey';
            columns: ['project_id'];
            isOneToOne: false;
            referencedRelation: 'projects';
            referencedColumns: ['id'];
          },
        ];
      };
    };
    Views: {
      [_ in never]: never;
    };
    Functions: {
      advance_stage: {
        Args: { p_next: Database['public']['Enums']['stage']; p_project: string };
        Returns: undefined;
      };
      client_project_id: { Args: Record<PropertyKey, never>; Returns: string };
      client_project_in: {
        Args: { p_stages: Database['public']['Enums']['stage'][] };
        Returns: boolean;
      };
      client_project_not_closed: { Args: Record<PropertyKey, never>; Returns: boolean };
      is_owner: { Args: Record<PropertyKey, never>; Returns: boolean };
      is_service_role: { Args: Record<PropertyKey, never>; Returns: boolean };
    };
    Enums: {
      answer_action: 'next_round' | 'immediate_fix';
      approver_role: 'owner' | 'client';
      artifact_status: 'draft' | 'approved' | 'superseded';
      asked_by: 'template' | 'agent';
      backlog_status: 'open' | 'answered' | 'assumption_accepted';
      change_decision: 'accept_current_round' | 'accept_mini_round' | 'defer' | 'decline';
      change_status: 'received' | 'accepted' | 'deferred' | 'declined' | 'deployed';
      close_reason: 'completed' | 'cancelled';
      comment_disposition: 'forwarded' | 'change_request' | 'ignored';
      comment_kind: 'prototype' | 'final_screenshots';
      gate_type: 'soft' | 'hard' | 'client';
      intake_round_status: 'open' | 'submitted' | 'reviewed';
      project_status: 'active' | 'paused' | 'closed';
      round_status: 'planned' | 'building' | 'in_review' | 'approved';
      run_approval_status: 'pending' | 'approved' | 'denied';
      run_status: 'queued' | 'running' | 'waiting' | 'succeeded' | 'failed' | 'cancelled';
      skill_mark: 'good' | 'bad';
      skill_scope: 'project' | 'candidate' | 'library' | 'deprecated';
      stage:
        | 'intake'
        | 'requirements'
        | 'plan'
        | 'prototype'
        | 'build_rounds'
        | 'qc_report'
        | 'deploy_prep'
        | 'handover'
        | 'closed';
      template_status: 'draft' | 'approved' | 'archived';
      upload_scan_status: 'pending' | 'clean' | 'infected';
    };
    CompositeTypes: {
      [_ in never]: never;
    };
  };
};

type DatabaseWithoutInternals = Omit<Database, '__InternalSupabase'>;

type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, 'public'>];

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema['Tables'] & DefaultSchema['Views'])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends (DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals;
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions['schema']]['Tables'] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions['schema']]['Views'])
    : never) = never,
> = DefaultSchemaTableNameOrOptions extends { schema: keyof DatabaseWithoutInternals }
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions['schema']]['Tables'] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions['schema']]['Views'])[TableName] extends {
      Row: infer R;
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema['Tables'] & DefaultSchema['Views'])
    ? (DefaultSchema['Tables'] & DefaultSchema['Views'])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R;
      }
      ? R
      : never
    : never;

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    keyof DefaultSchema['Tables'] | { schema: keyof DatabaseWithoutInternals },
  TableName extends (DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals;
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions['schema']]['Tables']
    : never) = never,
> = DefaultSchemaTableNameOrOptions extends { schema: keyof DatabaseWithoutInternals }
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions['schema']]['Tables'][TableName] extends {
      Insert: infer I;
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema['Tables']
    ? DefaultSchema['Tables'][DefaultSchemaTableNameOrOptions] extends {
        Insert: infer I;
      }
      ? I
      : never
    : never;

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    keyof DefaultSchema['Tables'] | { schema: keyof DatabaseWithoutInternals },
  TableName extends (DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals;
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions['schema']]['Tables']
    : never) = never,
> = DefaultSchemaTableNameOrOptions extends { schema: keyof DatabaseWithoutInternals }
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions['schema']]['Tables'][TableName] extends {
      Update: infer U;
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema['Tables']
    ? DefaultSchema['Tables'][DefaultSchemaTableNameOrOptions] extends {
        Update: infer U;
      }
      ? U
      : never
    : never;

export type Enums<
  DefaultSchemaEnumNameOrOptions extends
    keyof DefaultSchema['Enums'] | { schema: keyof DatabaseWithoutInternals },
  EnumName extends (DefaultSchemaEnumNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals;
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions['schema']]['Enums']
    : never) = never,
> = DefaultSchemaEnumNameOrOptions extends { schema: keyof DatabaseWithoutInternals }
  ? DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions['schema']]['Enums'][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema['Enums']
    ? DefaultSchema['Enums'][DefaultSchemaEnumNameOrOptions]
    : never;

export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends
    keyof DefaultSchema['CompositeTypes'] | { schema: keyof DatabaseWithoutInternals },
  CompositeTypeName extends (PublicCompositeTypeNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals;
  }
    ? keyof DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions['schema']]['CompositeTypes']
    : never) = never,
> = PublicCompositeTypeNameOrOptions extends { schema: keyof DatabaseWithoutInternals }
  ? DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions['schema']]['CompositeTypes'][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof DefaultSchema['CompositeTypes']
    ? DefaultSchema['CompositeTypes'][PublicCompositeTypeNameOrOptions]
    : never;

export const Constants = {
  public: {
    Enums: {
      answer_action: ['next_round', 'immediate_fix'],
      approver_role: ['owner', 'client'],
      artifact_status: ['draft', 'approved', 'superseded'],
      asked_by: ['template', 'agent'],
      backlog_status: ['open', 'answered', 'assumption_accepted'],
      change_decision: ['accept_current_round', 'accept_mini_round', 'defer', 'decline'],
      change_status: ['received', 'accepted', 'deferred', 'declined', 'deployed'],
      close_reason: ['completed', 'cancelled'],
      comment_disposition: ['forwarded', 'change_request', 'ignored'],
      comment_kind: ['prototype', 'final_screenshots'],
      gate_type: ['soft', 'hard', 'client'],
      intake_round_status: ['open', 'submitted', 'reviewed'],
      project_status: ['active', 'paused', 'closed'],
      round_status: ['planned', 'building', 'in_review', 'approved'],
      run_approval_status: ['pending', 'approved', 'denied'],
      run_status: ['queued', 'running', 'waiting', 'succeeded', 'failed', 'cancelled'],
      skill_mark: ['good', 'bad'],
      skill_scope: ['project', 'candidate', 'library', 'deprecated'],
      stage: [
        'intake',
        'requirements',
        'plan',
        'prototype',
        'build_rounds',
        'qc_report',
        'deploy_prep',
        'handover',
        'closed',
      ],
      template_status: ['draft', 'approved', 'archived'],
      upload_scan_status: ['pending', 'clean', 'infected'],
    },
  },
} as const;
