#!/usr/bin/env bash
# Regenerates packages/shared/src/database.types.ts from a live Postgres.
#   SUPABASE_DB_URL  connection string (default: the local Supabase started by `supabase start`)
# Run it after every change to supabase/migrations/, against a database that has them applied.
# Needs network access for `npx supabase`; no Docker is needed for a --db-url connection.
set -euo pipefail
repo="$(cd "$(dirname "$0")/.." && pwd)"
url="${SUPABASE_DB_URL:-postgresql://postgres:postgres@127.0.0.1:54322/postgres}"
out="$repo/packages/shared/src/database.types.ts"
tmp="$(mktemp)"
trap 'rm -f "$tmp"' EXIT
(cd "$repo" && npx --yes supabase gen types typescript --db-url "$url" --schema public) > "$tmp"
{
  echo "// GENERATED by scripts/gen-types.sh from the public schema. Do not edit by hand."
  cat "$tmp"
} > "$out"
(cd "$repo" && pnpm exec prettier --write "$out" >/dev/null)
echo "wrote $out"
